api_ieee:
  url: 'https://ieeexploreapi.ieee.org/api/v1'
  key: 'epr47e9r9zhk6wm2t5c22qf6  '
  path: '/search/articles'
  max_records: 200
  table: 'articles'
  page: 1

api_scid:
  url: 'https://api.elsevier.com'
  key: '7f59af901d2d86f78a1fd60c1bf9426a'
  path: '/content/search/sciencedirect'
  count: 100
  table: 'articles'
  page: 1
  httpAccept: application/json

search: ['big data', 'java']
# AND, OR, NOT
operator: 'OR'
# Extract, SQLile, BitText
mode: 'SQLile'
# IEEE, SCID
scope: 'SCID'

data:
  [
    'author',
    'title',
    'year',
    'isbn',
    'publisher',
    'address',
    'url',
    'doi',
    'abstract',
    'booktitle',
    'pages',
    'numpages',
    'keywords',
    'location',
    'series',
  ]
